export const FETCH_USER_FROM_API = "FETCH_USER_FROM_API";
export const CLEAN_USER_FROM_STATE = "CLEAN_USER_FROM_STATE";
export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";
export const SET_USER_LOGGED_OUT = "SET_USER_LOGGED_OUT";
export const SET_USER_UID = "SET_USER_UID";
